### ISSUE TITLE
It it no longer working on Win 11 version 22000.348?

### ISSUE THREAD

**Issue by ziloxaoki** [jetspiking/Taskbar11#13]
It seems that this patch is no longer working in latest Win 11 version (22000.348).
After updating windows the patch stopped working. Even after reinstalling and restarting the pc it sill doesn't work.
OS build: 22000.348
Windows Feature Experience Pack: 1000.22000.348.0

**Comment by ziloxaoki** [comment]
It can be fixed manually updating the os build version in the registry for the explorerpatcher:
https://github.com/valinet/ExplorerPatcher/issues/440

**Comment by jetspiking** [comment]
Thank you for reporting this issue! Currently I am on Dev Build  22499. However, I am not noticing any additional issues in this version. Please keep an eye out for updates, I suspect upcoming updates will resolve this issue.
