### ISSUE TITLE
Set taskbar on top at second screen

### ISSUE THREAD

**Issue by xhzwxhz** [jetspiking/Taskbar11#17]
Dear, first of all thank you for the effort.
I'm trying to set taskbar on top of every screen. But it only effect on the main display screen.
Could you plz help check this issue, thank you.

**Comment by GCCalin** [comment]
With latest release you need to toggle this option:
![image](https://user-images.githubusercontent.com/95024863/147446514-6b6efb4f-74fb-4e7b-9de9-a77e1941f931.png)

**Comment by xhzwxhz** [comment]
Hi, thank you for the reply. 
Taskbar did show on second screen. It’s just not at the same position on top as main screen. 
Do you mean “Equal taskbar position” should be flagged too? Thank you.

**Comment by jetspiking** [comment]
Hi! Thank you for opening this issue. The option "Equal Taskbar Positions" should be checked as well.

However, I just attempted to show the secondary taskbar on my own monitor and can verify it is no longer working like it should. I am not sure why this has changed, I will look into it.

In the meantime you could consider hiding the taskbar on your secondary monitor.

**Comment by jetspiking** [comment]
@xhzwxhz After adjusting the Taskbar options through Windows (I disabled and enabled automatically hide touchbar through Windows settings menu) the "Equal Taskbar Positions" from inside Taskbar11 is magically working again. Could you verify whether this also works on your system?

Something odd is going on with the registry settings which makes Taskbar11 work unreliable at times. At the moment I am not yet sure where the issue originates from.

**Comment by xhzwxhz** [comment]
Hi, @jetspiking, I just installed the latest version of Taskbar 11, and check "Equal taskbar positions", Taskbar on two screens are all on TOP now. It works. Thank you so much for the help.

**Comment by jetspiking** [comment]
Great to head the issue is resolved! If you notice other issues or the same issue feel free to open a new issue.
