### ISSUE TITLE
Window preview wont show if taskbar is on top

### ISSUE THREAD

**Issue by CosmicBlue2000** [jetspiking/Taskbar11#21]
Well, the titel says it all. If you dicide to put your taskbar on top of scrren, there wont be any previews for open windows anymore.
So if for example you have opened up three instances of Explorer, and all are minimized you can't see which one leads to which path.

This might perhaps be, because window preview is hardcoded to be above taskbar, so if taskbar is on top of screen, preview would be off screen.

**Comment by jetspiking** [comment]
Thank you for reporting this issue! At the moment there is no real solution. However, there a few workarounds. 

Please visit the following issue for more information about this problem:
https://github.com/jetspiking/Taskbar11/issues/9
