### ISSUE TITLE
I would like to uninstall Taskbar11 or Revert back to the original layout

### ISSUE THREAD

**Issue by Shpox** [jetspiking/Taskbar11#24]
Is this possible?

**Comment by jetspiking** [comment]
Hi there! 

To revert to the default layout, you should: 
- Set the taskbar position to "Bottom"
- Set the taskbar size to "Medium"
- Uncheck the setting (checkbox) "Use Old Context Menu"
- Click "Save"

All other settings can be adjusted through the Windows settings menu.

The application is portable, so deleting the .exe from your system will suffice. 

Let me know if you have any more questions.
