### ISSUE TITLE
right clic for old task bar menu + problem with clock and system icons

### ISSUE THREAD

**Issue by lyonelf** [jetspiking/Taskbar11#30]
Hi,

In my computer when i activate this is always the new one " task barres settings"

2nd issue: date and system icons are to much down and date is partly outside the screen

**Comment by jetspiking** [comment]
Hi there!

The option "Right click for old context menu" only changes the window that pops-up on the desktop or explorer. It does not change the option menu that is displayed when clicking on the taskbar itself.

Currently there is not a fix for the second issue. However, you can set the taskbar size to medium or large and then it will no longer fall off the taskbar.
