### ISSUE TITLE
Taskbar wont get small

### ISSUE THREAD

**Issue by Itz-Ravi03** [jetspiking/Taskbar11#31]
I clicked on big taskbar but now it wont revert back to normal

**Comment by jetspiking** [comment]
Hi there!

Did you adjust the taskbar-size and click save afterwards? If something goes wrong in restarting ''explorer.exe'' manually restarting Windows should fix the issue.

**Comment by Itz-Ravi03** [comment]
Yes i did.
I had a solution. I went to registry 
and changed it
