### ISSUE TITLE
Removing

### ISSUE THREAD

**Issue by meijeh15** [jetspiking/Taskbar11#32]
I am not tech savvy and this feature is not working for my personal use as I had hoped. How can I remove this from my desktop? I cannot find the exe file or program to remove it within my computer. Any assistance is much appreciated.

**Comment by jetspiking** [comment]
Hi there!

To revert to the default layout, you should:

    Set the taskbar position to "Bottom"
    Set the taskbar size to "Medium"
    Uncheck the setting (checkbox) "Use Old Context Menu For Right Mouse Button Click"
    Click "Save"

All other settings can be adjusted through the Windows settings menu.

The application is portable, so deleting the .exe from your system will suffice.

Let me know if you have any more questions.
