### ISSUE TITLE
Multiple monitor taskbar issues

### ISSUE THREAD

**Issue by kyoryo** [jetspiking/Taskbar11#4]
When taskbar position changed to top, the other monitor's taskbar except the main monitor's  taskbar still on bottom position.
Below is a screenshot image taken from my monitors (hi-res).
![explorer_2021-10-20_06-56-202](https://user-images.githubusercontent.com/5959062/138006798-9e0a9822-7650-4dd2-878c-e9824c5b02d7.jpg)

**Comment by jetspiking** [comment]
Thank you for reporting this issue! Luckily, this is one of the few issues I should be able to solve by editing the registry settings :).

I am going to work on the new release right away, I'll attempt to have it online in 1 hour.

**Comment by jetspiking** [comment]
I just published the new release. Under "Multi Monitor Taskbar" you should be able to adjust the settings to fix your Multi Monitor issues.

You can equal the taskbar position on these monitors, or disable showing the taskbar all together on secondary displays.
